// SPDX-License-Identifier: MIT
// FidelityFX GPU sort kernels. Requires wave operations (wavebasic).
// Utility kernels are in SplatUtilitiesCore.compute which has no wave op requirements.

// FidelityFX GPU sorting
#pragma kernel FfxParallelSortReduce
#pragma kernel FfxParallelSortScanAdd
#pragma kernel FfxParallelSortScan
#pragma kernel FfxParallelSortScatter
#pragma kernel FfxParallelSortCount

// GPU sorting needs wave ops
#pragma require wavebasic

#pragma use_dxc

#include "GpuSortFidelityFX.hlsl"